name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cpp-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.2.0
      with:
        submodules: true
    - name: Update package list
      run: sudo apt update
    - name: Install libssl-dev
      run: sudo apt install libssl-dev
    - name: Install cpp-check
      run: sudo apt install cppcheck
    - name: Run cpp-check
      run: cppcheck --enable=all -I include/ cpr/
